### ISSUE TITLE
[SOCKET.IO] Error: duplicate key value violates unique constraint "tasks_assignees_pk"

### ISSUE THREAD

**Issue by yonas** [Worklenz/worklenz#25]
```sh
GET /api/v1/task-time-log/task/b8c817b7-a6b0-43d5-8144-91f47728e12d 304 19.237 ms - -
Trace: [SOCKET.IO] Error: duplicate key value violates unique constraint "tasks_assignees_pk"
    at /home/yonas/git/worklenz/worklenz-backend/node_modules/pg-pool/index.js:45:11
    at tryCatcher (/home/yonas/git/worklenz/worklenz-backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/yonas/git/worklenz/worklenz-backend/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/yonas/git/worklenz/worklenz-backend/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/yonas/git/worklenz/worklenz-backend/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/yonas/git/worklenz/worklenz-backend/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/yonas/git/worklenz/worklenz-backend/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/yonas/git/worklenz/worklenz-backend/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/yonas/git/worklenz/worklenz-backend/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/home/yonas/git/worklenz/worklenz-backend/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21) {
  severity: 'ERROR',
  code: '23505',
  messageDetail: 'Key (task_id, project_member_id)=(b8c817b7-a6b0-43d5-8144-91f47728e12d, 60162685-02d7-4043-a88a-f3b60923c1b9) already exists.',
  where: 'SQL statement "INSERT INTO tasks_assignees (task_id, project_member_id, team_member_id, assigned_by)\n' +
    '    VALUES (_task_id, _project_member_id, _team_member_id, _reporter_user_id)"\n' +
    'PL/pgSQL function create_task_assignee(uuid,uuid,uuid,uuid) line 30 at SQL statement',
  schema: 'public',
  table: 'tasks_assignees',
  constraint: 'tasks_assignees_pk',
  file: 'nbtinsert.c',
  line: '671',
  routine: '_bt_check_unique'
}
    at log_error (/home/yonas/git/worklenz/worklenz-backend/build/socket.io/util.js:12:13)
    at on_quick_assign_or_remove (/home/yonas/git/worklenz/worklenz-backend/build/socket.io/commands/on-quick-assign-or-remove.js:63:30)
```

**Comment by Nadeera3784** [comment]
Hi @yonas ,
It appears that you are attempting to assign a user to a task who is already assigned. The record already exists in the database, causing a duplicate key value violation. This should be handled by the code itself by checking if the record already exists before attempting to insert it.

To resolve this issue, you have a couple of options:

- Remove and Reassign: Remove the user from the task and then reassign them.
- Delete and Reinsert: Delete the existing record from the database and then assign again.
