### ISSUE TITLE
How to avoid using AWS during account signup verification

### ISSUE THREAD

**Issue by yonas** [Worklenz/worklenz#7]
I can't login because worklenz wants to send a verification email via AWS.

How can I bypass this? For eg. create an environment variable in .env to skip email verification for new user account registrations.

```sh
InvalidClientTokenId: The security token included in the request is invalid.
    at throwDefaultError (/home/yonas/git/worklenz/worklenz-backend/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /home/yonas/git/worklenz/worklenz-backend/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_SendEmailCommandError (/home/yonas/git/worklenz/worklenz-backend/node_modules/@aws-sdk/client-ses/dist-cjs/protocols/Aws_query.js:2373:20)
    at async /home/yonas/git/worklenz/worklenz-backend/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /home/yonas/git/worklenz/worklenz-backend/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at async /home/yonas/git/worklenz/worklenz-backend/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /home/yonas/git/worklenz/worklenz-backend/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async sendEmail (/home/yonas/git/worklenz/worklenz-backend/build/shared/email.js:71:21) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    requestId: 'c70db73d-26f8-4313-ba64-a5f1b7adc694',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Type: 'Sender',
  Code: 'InvalidClientTokenId'
}
```

**Comment by dhilgarth** [comment]
Email sending should be configurable via simple SMTP parameters, especially because getting a production AWS SES takes some effort.

**Comment by yonas** [comment]
This seems to have been fixed.
